### ISSUE TITLE
Some words are getting multiple hljs classes?

### ISSUE THREAD

**Issue by jcv8000** [b-kelly/prosemirror-highlightjs#4] opened 2020-09-02 05:23 UTC
Hey, this is a really awesome plugin and I wanted to say thank you because it made my life a hell of a lot easier.

I was just testing different themes and I realized that some of the words in the code blocks like "public static void Main()" were plain white. I used inspect element and saw that most words in the code block are getting multiple hljs CSS classes (mostly `hljs-class`, `hljs-title` and `hljs-function`) on top of their correct css class. Some whitespace characters are also getting the `hljs-class` class.

And this is causing highlighted code to have the wrong colors in some places

For comparison I made a regular highlight.js block outside of prosemirror and every word is only getting a max of 1 hljs CSS class.

I was just wondering if there was something that I need to change in my project or if this was a bug?

Edit: by the way I'm using prosemirror-example-setup and sticking this plugin in that setup, not writing my own plugin like the 2nd example in the readme

**Comment by b-kelly** [comment] 2020-09-03 00:54
Hmm... Sounds like a bug to me. I'll take a look into it and let you know soon. I _knew_ I should have finished the unit tests that check the underlying class names on each token...

Thanks for the report!

**Comment by jcv8000** [comment] 2020-09-03 04:05
That would be awesome, thank you

**Comment by b-kelly** [comment] 2020-09-04 01:18
I'm able to reproduce your issue in my very own demo editor (in this project). However, I have yet to reproduce with a test. It looks like my `getHighlightDecorations` performs exactly as it should, converting the array of decorations to a `DecorationSet` creates a slight difference, but not the one we're observing in the editor. I have a theory that this might be an upstream issue, but it could also be me mapping the decorations incorrectly at some point.

I'll keep looking into this. I have a few [test cases](https://github.com/b-kelly/prosemirror-highlightjs/blob/master/test/getHighlightDecorations.test.ts#L151) written if you're curious about the state of things.

**Comment by b-kelly** [comment] 2020-09-05 01:45
@jcv8000 I looked into this a bit more and I am sorry to report that this is working "correctly". Looking at the [documentation](https://prosemirror.net/docs/ref/#view.Decoration^inline) of inline decorations (emphasis mine):

>  Creates an inline decoration, which adds the given attributes to **each inline node** between from and to

This makes some amount of sense because it ensures that the node content stays relatively flat and keeps the complexity down when placing decorations around ranges of existing nodes. The unfortunate consequence is that existing hljs themes that rely on nesting selectors will not apply correctly.

To illustrate what this looks like, consider the following scenario:

```html
<span class="hljs-function">
    <span class="hljs-keyword">function</span> <span class="hljs-title">$initHighlight</span>(<span class="hljs-params">block, cls</span>)
</span>
```

will be "flattened" and become:

```html
<span class="hljs-keyword hljs-function">function</span><span class="hljs-function"> </span><span class="hljs-title hljs-function">$initHighlight</span><span class="hljs-function">(</span><span class="hljs-params hljs-function">block, cls</span><span class="hljs-function">) </span>
```

Note how the wrapping `hljs-function` element was placed onto every child node created by the "nested" decorations, wrapping even plain text when they were not otherwise affected by another decoration.

As far as I can tell, this is not a problem I can fix. In theory, I could move over to using marks (which respect distinct, overlapping marks), but that would require dynamically modifying the document's schema. In addition, the plugin will stop being "transparent", adding content directly into the document (which will affect things like copy/paste, parsing, etc).

Unfortunately, I'm going to have to close this issue, but I'll add a note to the README listing this as a gotcha. I'll also be keeping a lookout for potential solutions and update this issue if I ever come up with one.

**Closed by b-kelly** 2020-09-05 01:45 UTC

**Comment by jcv8000** [comment] 2020-09-05 22:24
Okay, I do understand what's happening now. That illustration that you gave helped out. I appreciate you looking into this for me

So I guess the only thing I could really do would be to edit the themes to make sure the class that would normally be a parent doesn't override the class that is meant to be changing the text color. But that would be a ton of work to do that for every single style, so I might just have to leave it like this for now

Again thanks for looking into this for me, I understand the layout now

**Comment by jcv8000** [comment] 2020-09-05 22:50
This is just one last idea, so in your example it adds the `hljs-function` class to every child in the "nested" decoration.

Would it be possible to check each one and make sure it _doesn't_ already have a class to begin with before adding that "wrapping" class?
I can see in the html structure that the "wrapping" class is added _after_ the regular class. If it could somehow avoid adding the wrapper to nodes that were already assigned a class, the nodes that already have classes would go unaffected, and whitespace characters and plain text (like the parenthesis in your example) would receive that "wrapping" class to give them the correct static color.

I have no idea how that would be handled, just wondering if that could improve anything
